name: tekartik_test_menu_io
version: 0.8.0+3
homepage: https://github.com/tekartik/test_menu.dart
# https://github.com/tekartik/tekartik_test_menu.dart
description: Simple io test menu

publish_to: none
environment:
  sdk: ^3.6.0
dependencies:
  args: ">=2.6.0"
  dev_build: ">=1.1.2"
  process_run: ">=1.2.1+1"
  tekartik_test_menu:
    git:
      url: https://github.com/tekartik/test_menu.dart
      ref: dart3a
      path: test_menu
    version: '>=0.8.0'
#  tekartik_pub:
#    git:
#      url: https://github.com/tekartik/pub.dart
#      ref: dart3a

dev_dependencies:
  test: ">=1.24.0"

resolution: workspace
  # dev_build:
  #  path: ../../../tekartik/dev_test.dart/dev_build
#  tekartik_mdl_js:
#    path: /opt/devx/git/github.com/alextekartik/mdl_js.dart
#  platform_context:
#    # path: /opt/devx/git/github.com/tekartik/platform_context.dart
#    path: /opt/devx/git/github.com/alextekartik/platform_context.dart
