name: tekartik_test_menu_browser
version: 0.9.0
homepage: https://github.com/tekartik/test_menu.dart
# https://github.com/tekartik/tekartik_test_menu.dart
description: Simple test menu

publish_to: none

environment:
  sdk: '>=3.3.0 <4.0.0'
dependencies:
  tekartik_test_menu:
    git:
      url: https://github.com/tekartik/test_menu.dart
      ref: dart3a
      path: test_menu
    version: '>=0.8.0'
  tekartik_test_menu_io:
    git:
      url: https://github.com/tekartik/test_menu.dart
      ref: dart3a
      path: test_menu_io
    version: '>=0.8.0'
  tekartik_mdl_js:
    git:
      url: https://github.com/tekartik/mdl_js.dart
      ref: dart3a
    version: '>=0.4.0+1'
  tekartik_browser_utils:
    git:
      url: https://github.com/tekartik/browser_utils.dart
      ref: dart3a
    version: '>=0.6.8+1'
  tekartik_platform_browser:
    git:
      url: https://github.com/tekartik/platform.dart
      path: platform_browser
      ref: dart3a

dev_dependencies:
  process_run: '>=0.10.0+1'
  dev_test: any
  test: any
  path:
  build_runner: '>=0.9.0'
  build_test: '>=0.10.2'
  build_web_compilers: '>=0.4.0'
  dev_build: '>=0.16.5-0'

dependency_overrides:
  tekartik_test_menu:
    path: ../test_menu
  tekartik_test_menu_io:
    path: ../test_menu_io
  # dev_build:
  #  path: ../../../tekartik/dev_test.dart/dev_build

#  tekartik_mdl_js:
#    path: /opt/devx/git/github.com/alextekartik/mdl_js.dart
#  platform_context:
#    # path: /opt/devx/git/github.com/tekartik/platform_context.dart
#    path: /opt/devx/git/github.com/alextekartik/platform_context.dart
