name: tekartik_test_menu_browser
version: 0.6.0
homepage: https://github.com/tekartik/test_menu.dart
# git://github.com/tekartik/tekartik_test_menu.dart
description: Simple test menu

publish_to: none

environment:
  sdk: '>=2.12.0-259.16.beta <3.0.0'
dependencies:
  tekartik_test_menu:
    git:
      url: git://github.com/tekartik/test_menu.dart
      ref: null_safety
      path: test_menu
    version: '>=0.6.0'
  tekartik_mdl_js:
    git:
      url: git://github.com/tekartik/mdl_js.dart
      ref: null_safety
    version: '>=0.4.0+1'
  tekartik_browser_utils:
    git:
      url: git://github.com/tekartik/browser_utils.dart
      ref: null_safety
    version: '>=0.6.8+1'
  tekartik_platform_browser:
    git:
      url: git://github.com/tekartik/platform.dart
      path: platform_browser
      ref: null_safety

dev_dependencies:
  process_run: '>=0.10.0+1'
  grinder: any
  dev_test: any
  test: any
  tekartik_pub:
    git:
      url: git://github.com/tekartik/pub.dart
      ref: null_safety
  chrome_travis:
    git:
      url: git://github.com/tekartik/chrome_travis.dart
      ref: null_safety
    version: '>=0.1.3'
  tekartik_deploy:
    git:
      url: git://github.com/tekartik/deploy.dart
      ref: null_safety
  build_runner: '>=0.9.0'
  build_test: '>=0.10.2'
  build_web_compilers: '>=0.4.0'

dependency_overrides:
  tekartik_test_menu:
    path: ../test_menu
  # temp nnbd
  # build_runner: '<2.0.0'
  # build_web_compilers: '<3.0.0'

#  tekartik_mdl_js:
#    path: /opt/devx/git/github.com/alextekartik/mdl_js.dart
#  platform_context:
#    # path: /opt/devx/git/github.com/tekartik/platform_context.dart
#    path: /opt/devx/git/github.com/alextekartik/platform_context.dart