name: tekartik_test_menu_browser
version: 0.9.0
homepage: https://github.com/tekartik/test_menu.dart
# https://github.com/tekartik/tekartik_test_menu.dart
description: Simple test menu

publish_to: none

environment:
  sdk: ^3.8.0
dependencies:
  tekartik_test_menu:
    git:
      url: https://github.com/tekartik/test_menu.dart
      ref: dart3a
      path: test_menu
    version: '>=0.8.0'
  tekartik_test_menu_io:
    git:
      url: https://github.com/tekartik/test_menu.dart
      ref: dart3a
      path: test_menu_io
    version: '>=0.8.0'
  tekartik_mdl_js:
    git:
      url: https://github.com/tekartik/mdl_js.dart
      ref: dart3a
    version: '>=0.4.0+1'
  tekartik_browser_utils:
    git:
      url: https://github.com/tekartik/browser_utils.dart
      ref: dart3a
    version: '>=0.6.8+1'
  tekartik_platform_browser:
    git:
      url: https://github.com/tekartik/platform.dart
      path: platform_browser
      ref: dart3a
  web: '>=0.5.1'
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
      ref: dart3a
dev_dependencies:
  tekartik_app_web_build:
    git:
      url: https://github.com/tekartik/app_web_utils.dart
      ref: dart3a
      path: packages/app_build
    version: '>=0.0.1'
  process_run: ">=1.2.1+1"
  test: ">=1.24.0"
  path: ">=1.9.0"
  build_runner: ">=2.4.13"
  build_test: '>=0.10.2'
  build_web_compilers: ">=4.0.11"
  dev_build: ">=1.1.2"

resolution: workspace
  # dev_build:
  #  path: ../../../tekartik/dev_test.dart/dev_build

#  tekartik_mdl_js:
#    path: /opt/devx/git/github.com/alextekartik/mdl_js.dart
#  platform_context:
#    # path: /opt/devx/git/github.com/tekartik/platform_context.dart
#    path: /opt/devx/git/github.com/alextekartik/platform_context.dart
