name: tekartik_test_menu
version: 0.8.0
homepage: https://github.com/tekartik/test_menu.dart
# https://github.com/tekartik/tekartik_test_menu.dart
description: Simple test menu

publish_to: none

environment:
  sdk: ^3.6.0
dependencies:
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
      ref: dart3a
    version: '>=0.10.3'
  matcher: any
  meta: ">=1.15.0"
  stack_trace:
  dev_build: ">=1.1.2"

dev_dependencies:
  process_run: ">=1.2.1+1"
  test: ">=1.24.0"
  tekartik_browser_utils:
    git:
      url: https://github.com/tekartik/browser_utils.dart
      ref: dart3a
    version: '>=0.5.0'

resolution: workspace
#  dev_build:
#    path: ../../../tekartik/dev_test.dart/dev_build
#  tekartik_mdl_js:
#    path: /opt/devx/git/github.com/alextekartik/mdl_js.dart
#  platform_context:
#    # path: /opt/devx/git/github.com/tekartik/platform_context.dart
#    path: /opt/devx/git/github.com/alextekartik/platform_context.dart
