name: tekartik_test_menu
version: 0.8.0
homepage: https://github.com/tekartik/test_menu.dart
# https://github.com/tekartik/tekartik_test_menu.dart
description: Simple test menu

publish_to: none

environment:
  sdk: '>=2.18.0 <3.0.0'
dependencies:
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
      ref: dart2_3
    version: '>=0.10.3'
  matcher: any
  meta: any
  stack_trace:

dev_dependencies:
  process_run: '>=0.10.0+1'
  dev_test: any
  test: any
  tekartik_browser_utils:
    git:
      url: https://github.com/tekartik/browser_utils.dart
      ref: dart2_3
    version: '>=0.5.0'

dependency_overrides:
#  tekartik_mdl_js:
#    path: /opt/devx/git/github.com/alextekartik/mdl_js.dart
#  platform_context:
#    # path: /opt/devx/git/github.com/tekartik/platform_context.dart
#    path: /opt/devx/git/github.com/alextekartik/platform_context.dart