name: tekartik_test_menu_example
version: 0.6.1
homepage: https://github.com/tekartik/test_menu.dart
# https://github.com/tekartik/tekartik_test_menu.dart
description: Simple test menu example

publish_to: none

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  process_run:
  test: '>=1.0.0'
  tekartik_test_menu_browser:
    git:
      url: https://github.com/tekartik/test_menu.dart
      path: test_menu_browser
      ref: dart2_3
    version: '>=0.4.7'
  tekartik_test_menu_io:
    git:
      url: https://github.com/tekartik/test_menu.dart
      path: test_menu_io
      ref: dart2_3
    version: '>=0.4.7'

dev_dependencies:
  build_runner: ">=0.10.0"
  build_test: '>=0.10.2'
  build_web_compilers: ">=0.4.0"

dependency_overrides:
  tekartik_test_menu_io:
    path: ../test_menu_io
  tekartik_test_menu_browser:
    path: ../test_menu_browser
  tekartik_test_menu:
      path: ../test_menu

#  tekartik_mdl_js:
#    path: /opt/devx/git/github.com/alextekartik/mdl_js.dart
#  platform_context:
#    # path: /opt/devx/git/github.com/tekartik/platform_context.dart
#    path: /opt/devx/git/github.com/alextekartik/platform_context.dart